script: "bundle exec rake test"
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - Gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-3.0.x
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-3.2.x
  allow_failures:
    - rvm: rbx-2
